### ISSUE TITLE
plugin won't open 

### ISSUE THREAD

**Issue by hardsiamang655** [Nukkit-coders/EconomyAPI#5]
17:17:03 [ERROR] Throwing
java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/nimbusds/jose/shaded/json/JSONValue
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:440) [Nukkit.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:750) [Nukkit.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:739) [Nukkit.jar:?]
        at cn.nukkit.Server.<init>(Server.java:582) [Nukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [Nukkit.jar:?]
Caused by: java.lang.NoClassDefFoundError: com/nimbusds/jose/shaded/json/JSONValue
        at me.onebone.economyapi.EconomyAPI.importLanguages(EconomyAPI.java:476) ~[?:?]
        at me.onebone.economyapi.EconomyAPI.initialize(EconomyAPI.java:429) ~[?:?]
        at me.onebone.economyapi.EconomyAPI.onEnable(EconomyAPI.java:411) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[Nukkit.jar:?]
        ... 4 more
Caused by: java.lang.ClassNotFoundException: com.nimbusds.jose.shaded.json.JSONValue
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_252]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28) ~[Nukkit.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
        at me.onebone.economyapi.EconomyAPI.importLanguages(EconomyAPI.java:476) ~[?:?]
        at me.onebone.economyapi.EconomyAPI.initialize(EconomyAPI.java:429) ~[?:?]
        at me.onebone.economyapi.EconomyAPI.onEnable(EconomyAPI.java:411) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[Nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[Nukkit.jar:?]
        ... 4 more
17:17:03 [INFO ] Disabling EconomyAPI v2.0.2

**Comment by PetteriM1** [comment]
Update Nukkit
