### ISSUE TITLE
FATAL

### ISSUE THREAD

**Issue by whes1015** [Nukkit-coders/EconomyAPI#6]
09:14:06 [INFO ] 開啟中... EconomyAPI v2.0.2
09:14:06 [FATAL] An error occurred while enabling the plugin EconomyAPI, 2.0.2, me.onebone.economyapi.EconomyAPI
java.lang.NoClassDefFoundError: com/nimbusds/jose/shaded/json/JSONValue
        at me.onebone.economyapi.EconomyAPI.importLanguages(EconomyAPI.java:476) ~[?:?]
        at me.onebone.economyapi.EconomyAPI.initialize(EconomyAPI.java:429) ~[?:?]
        at me.onebone.economyapi.EconomyAPI.onEnable(EconomyAPI.java:411) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:101) ~[powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:120) ~[powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:461) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:940) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:929) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at cn.nukkit.Server.<init>(Server.java:767) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:199) [powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
Caused by: java.lang.ClassNotFoundException: com.nimbusds.jose.shaded.json.JSONValue
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_301]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:43) ~[powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:27) ~[powernukkit-1.5.2.0-PN-SNAPSHOT-shaded.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        ... 10 more
09:14:06 [INFO ] 關閉中... EconomyAPI v2.0.2

**Comment by egor-erm** [comment]
yes
